//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fractions
    {
        public int Id { get; set; }
        public string LTSRid { get; set; }
        public double East { get; set; }
        public double North { get; set; }
        public string Name { get; set; }
    }
}
